rpm: Save and test the explicit package version
So we don't test packages from the repository that might have a newer
version!

diff --git a/templates/scripts/rpm_test.sh.erb b/templates/scripts/rpm_test.sh.erb
--- a/templates/scripts/rpm_test.sh.erb
+++ b/templates/scripts/rpm_test.sh.erb
@@ -41,14 +41,32 @@ EOF"
     ;;
 esac
 
+if [ ! -f archive/"${project}"-package.version ]; then
+  echo "archive/${project}-package.version artifact is required!" >&2
+  exit 1
+fi
+package_version=$(cat archive/"${project}"-package.version | tr -d '\r\n')
+
 # Helper to install packages
 install_package() {
+  versioned=1
+  if [ "$1" = "-n" ] || [ "$1" = "--no-version" ]; then
+    shift
+    versioned=0
+  fi
+
+  packages=()
+  for package in "$@"
+  do
+    packages+="${package}-${package_version}"
+  done
+
   case "$os" in
     centos|fedora)
-      sudo setarch "$target_arch" yum install -y "$@"
+      sudo setarch "$target_arch" yum install -y "${packages[@]}"
       ;;
     sles|opensuse)
-      sudo setarch "$target_arch" zypper install -y "$@"
+      sudo setarch "$target_arch" zypper install -y "${packages[@]}"
       ;;
     *)
       echo "OS $os not supported in testing - package install..." >&2
